name: Benchmark

on: [push, pull_request]
jobs:
  Benchmark:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Build benchmark
      run: dotnet build Tests/DotnetBenchmark || dotnet build Tests/DotnetBenchmark || dotnet build Tests/DotnetBenchmark
    - name: Benchmark
      run: dotnet run -p Tests/DotnetBenchmark -c Release
