name: 'C++ Build'

on: [push, pull_request]
jobs:
  AngouriMathCpp:

    strategy:
        matrix:
          include:
          - os: windows-latest
            flag: win-x64
          - os: ubuntu-latest
            flag: linux-x64
          - os: macos-latest
            flag: osx-x64
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
        
    - name: 'Generating exports'
      run: |
        cd Sources/Utils
        dotnet run -p Utils ExportsGenerator
        
    - name: 'Install some libs for Linux'
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install libcurl4-openssl-dev zlib1g-dev libkrb5-dev

    - name: 'Building the library into native'
      run: |
        cd Sources/Wrappers/AngouriMath.CPP.Exporting
        mkdir ../AngouriMath.CPP.Importing/out-x64
        
        dotnet publish -p:NativeLib=Shared -p:SelfContained=true -r ${{ matrix.flag }} -c release
        
    - name: 'Building AngouriMath.Importing'
      run: |
        cd Sources/Wrappers/AngouriMath.CPP.Importing
        cmake -S . -B build
        cmake --build build

