name: 'C++ test'

on: [push, pull_request]
jobs:
  Testing:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: 'Building the library into native'
      run: |
        cd Sources/Wrappers/AngouriMath.CPP.Exporting
        mkdir ../AngouriMath.CPP.Importing/win-x64
        dotnet publish -p:NativeLib=Shared -p:SelfContained=true -r win-x64 -c release
    - name: 'Running tests'
      run: |
        cd Sources/Tests/CPPWrapperUnitTests/tests
        cmake -S . -B build
        cmake --build build
        cd build
        ctest
