name: 'C# Test'

on: [push, pull_request]
jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Setup .NET 5 # The dotnet CLI above is replaced by this but the runtime is kept
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'

    - name: Build Tests # We need it to be able to retry
      run: |
        dotnet add "Sources/Tests/UnitTests" package Microsoft.NET.Test.Sdk # Update is required for GitHubActionsTestLogger to print anything
        dotnet add "Sources/Tests/UnitTests" package GitHubActionsTestLogger
        dotnet add "Sources/Tests/UnitTests" package coverlet.msbuild
        dotnet build Sources/Tests/UnitTests || dotnet build Tests/UnitTests || dotnet build Tests/UnitTests

    - name: Test
      run: |
        dotnet test "Sources/Tests/UnitTests" -c Release -l GitHubActions /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Info about the coverage report
      if: ${{ matrix.os == 'windows-latest' }}
      run: dir ./Sources/Tests/UnitTests/coverage.opencover.xml

    - name: Send to codecov
      if: ${{ matrix.os == 'windows-latest' }}
      uses: codecov/codecov-action@v1
      with:
        file: ./Sources/Tests/UnitTests/coverage.opencover.xml
