name: FSharpTest

on: [push, pull_request]
jobs:
  Test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Setup .NET 5 # The dotnet CLI above is replaced by this but the runtime is kept
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Build Tests # We need it to be able to retry
      run: |
        dotnet add "Tests/FSharpWrapperUnitTests" package Microsoft.NET.Test.Sdk # Update is required for GitHubActionsTestLogger to print anything
        dotnet add "Tests/FSharpWrapperUnitTests" package GitHubActionsTestLogger
        dotnet build Tests/FSharpWrapperUnitTests
    - name: Test
      run: |
        dotnet test "Tests/FSharpWrapperUnitTests" -c Release -l GitHubActions