name: 'Interactive Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Setup .NET 6 # The dotnet CLI above is replaced by this but the runtime is kept
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.5'

    - name: Build
      run: |
        cd Sources/Wrappers
        dotnet build AngouriMath.Interactive
