name: 'Upload last-master versions to MyGet'

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
          
      - uses: actions/checkout@v2
        
      - name: 'Pack AngouriMath'
        run: |
          cd Sources
 
          # versioning
          commithash=$(git rev-parse --short HEAD)
          currtime=$(date +%s)
          echo "commit hash is $commithash"
          echo "time is $currtime"
          name=0.0.0-master-$currtime-$commithash
          echo "name is $name"
          
          # AngouriMath
          cd AngouriMath
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push AngouriMath.$name.nupkg --api-key ${{ secrets.MYGET_KEY }} --source "myget"
          cd ../../..
          
          # AngouriMath.FSharp
          cd Wrappers/AngouriMath.FSharp
          dotnet restore
          dotnet build -c Release
          dotnet pack -c Release -p:PackageVersion=$name
          cd bin/Release
          dotnet nuget push AngouriMath.FSharp.$name.nupkg --api-key ${{ secrets.MYGET_KEY }} --source "myget"
          cd ../../../..
          
          # AngouriMath.Interactive
          cd Wrappers/AngouriMath.Interactive
          dotnet restore
          dotnet build -c Release
          dotnet pack -c Release -p:PackageVersion=$name
          cd bin/Release
          dotnet nuget push AngouriMath.Interactive.$name.nupkg --api-key ${{ secrets.MYGET_KEY }} --source "myget"
          cd ../../../..
