name: 'Upload last-master versions to GH Packages'

on:
  push:
    branches:
      - gh-packages-preview   # for a test

jobs:
  main:
    runs-on: ubuntu-latest    # the fastest
    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - uses: actions/checkout@v2
      - name: 'Pack AngouriMath'
        runs: |
          cd Sources/AngouriMath
          dotnet --pack -c release
          dotnet nuget add source --username WhiteBlackGoose --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
          cd bin/Release
          dotnet nuget push AngouriMath.1.3.0-preview.4.nupkg --api-key ${{ secrets.PACKAGES }}
